### ISSUE TITLE
Default commands

### ISSUE THREAD

**Issue by alerque** [stefansundin/powermate-linux#18]
Being able to override the default actions with shell commands is *great*, but I'm having trouble getting the configuration I want. I would like to change the press command which defaults to mute to play/pause, and the long press to be mute. I can map the press action just fine. The trouble is I can't figure out the syntax to access one of the default actions from a different event.

Can you document in the config file commentary how to e.g. connect "long_press_command" to "mute/unmute"?

**Comment by stefansundin** [comment]
Hi!

At the moment the `*_command` settings can only execute commands. Unfortunately, it is not possible to re-map to other built-in functionality.

You could try the following:

```toml
long_press_command = "xdotool key XF86AudioMute"

# or:

long_press_command = "amixer set Master toggle"
```

The experience should be fairly similar, but there may be subtle differences. Please let me know if you need more assistance.
